### ISSUE TITLE
Disabling/enabling TV as a display device crashes the app

### ISSUE THREAD

**Issue by CntZer0** [xenolightning/AudioSwitcher#10]
I'm using Windows 8 enterprise 64bit, running the app with admin rights. I have a TV plugged into my gpu hdmi output, so it acts as a video and an audio device at the same time. Whenever I change my display mode (PC only, Extend, Second screen only) so that the TV is toggled (win+P) right clicking the AudioSwitcher makes it blink in and out and becomes unusable. I have to kill the process and restart. Looking into this would be much appreciated, your app is the best one I found so far. Let me know if I can provide any more details.

**Comment by xenolightning** [comment]
This is a tough one.

It may be related to a known issue where the application is trying to load invalid audio devices. It usually happens when drivers are updated, but it could also be happening when switching to the TV.

Keep a look out for 1.6.4.1, it will include the fix for this.

**Comment by CntZer0** [comment]
Will do, hopefully it will solve it.

Thanks for your response!
