### ISSUE TITLE
[feature request] Device toggle

### ISSUE THREAD

**Issue by CntZer0** [xenolightning/AudioSwitcher#11]
An option to have one shortcut to toggle between devices, instead of having a shortcut per device.
Some sort of prompt on which device has been changed to would also be nice, preferably not as a taskbar notification.

**Comment by xenolightning** [comment]
Related to: https://github.com/xenolightning/AudioSwitcher_v1/issues/607

V2.0 has this, and is feature complete.

What did you have in mind regarding a notification? There's been a request to play a sound after the switch. But a bubble notification seems like the most logical solution.

**Comment by CntZer0** [comment]
Great to hear! Any ETA on v2?

I was thinking something akin to the notifications when you change your monitor settings on the monitor itself. So just like a widget or a borderless window with the name of the device you switched to maybe?

**Comment by CntZer0** [comment]
And I just realized I opened these in the wrong depository, sorry about that.
