### ISSUE TITLE
Disconnected blue tooth devices

### ISSUE THREAD

**Issue by Stephanowicz** [xenolightning/AudioSwitcher#12]
Hi,
I'm not quite sure if this is the right place to put a request...
anyways - thank You very much for this app!

I wonder, if it's possible to connect disabled BT-devices ?
- thats the main reason why I was looking for such an app.
Nobody seems to have managed that, yet...

Cheers,

Stephan

**Comment by xenolightning** [comment]
Enabling the device is easy enough, but getting it to connect requires an application to manage bluetooth devices.

It also may change per device, so it's probably best left to the manufacturer of the bluetooth device.

**Comment by Stephanowicz** [comment]
Well, I was thinking of the command in the context menu of the device in the Sound device listing. I think it should be possible in the same context of the api call for activating devices... the Windows api should manage the connecting via the bt Driver.

**Comment by xenolightning** [comment]
Enabling/Disabling the device is somewhat trivial.

I'm not sure if that will work in this scenario. Is the BT audio device disabled in Device Manager?

There's very little you can actually control through the Windows Api layer. It's great for finding and rendering an audio stream, not much more.
