### ISSUE TITLE
Windows 10 - IPolicyConfig GUID change.

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher#13]
>I don't know if you will have time to look at a bug that appears on a beta OS.
However if you can provide a debug version with more trace, I would like to understand why it doesn't work!

>EDIT: this may help:
>davkean/audio-switcher#32
> @neFast

Related Issue: xenolightning/AudioSwitcher_v1#850

**Comment by xenolightning** [comment]
```
[Guid("00000000-0000-0000-C000-000000000046"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
```

**Comment by xenolightning** [comment]
May create another interface, and class for this, to ensure backwards compatibility.

**Comment by neFAST** [comment]
cool, is rc2 up to date?
