### ISSUE TITLE
When library is started with device turned off, it does not fire VolumeChange events when it is later turned on

### ISSUE THREAD

**Issue by YusakuCz** [xenolightning/AudioSwitcher#16]
When the library is started with an audio device in "NotPresent/Unplugged" state, the VolumeChange events are not fired when this device is turned on later.

This is caused by GetAudioEndpointVolume called only in CoreAudioDevice constructor. It should be called in EnumeratorOnAudioDeviceChanged as well.

Quick - but working - fix that made the library work as expected for me - run the following in EnumeratorOnAudioDeviceChanged:

            ComThread.BeginInvoke(() =>
            {
                LoadProperties(_device);
                if (AudioMeterInformation == null)
                {
                    GetAudioMeterInformation(_device);
                }
                if (AudioEndpointVolume == null)
                {
                    GetAudioEndpointVolume(_device);
                    if (AudioEndpointVolume != null)
                        AudioEndpointVolume.OnVolumeNotification += AudioEndpointVolume_OnVolumeNotification;
                }
            })

**Comment by xenolightning** [comment]
Overhauled the event system.

When a device state change happens it will ensure that the audio information is available, and 'reset' it.

It should make the audio available regardless of state changes.

A bonus to this is that it will clear the volume information when the device state is disconnected.
