### ISSUE TITLE
Windows 10 build 10586.11  "Threshold 2 1511"- IPolicyConfig GUID change

### ISSUE THREAD

**Issue by anna254** [xenolightning/AudioSwitcher#18]
I am wondering how you find out the internal GUID. Which tools are you using?

Best regards
Anna

**Comment by xenolightning** [comment]
I've pulled it from other open source projects up until now.

The quick fix is to use the IUnkown Guid as the interface signature still remains the same.

The GUID has been update in the AudioSession branch, which isn't far away from a Pull & Merge into master.

**Comment by xenolightning** [comment]
Fixed with https://github.com/xenolightning/AudioSwitcher/pull/19
