### ISSUE TITLE
PolicyConfigClient CIID Change - Redstone 1

### ISSUE THREAD

**Issue by sebastso** [xenolightning/AudioSwitcher#26]
Looks like policy config 870AF99C-171D-4F9E-AF0D-E63DF40C2BC9 has been changed in Redstone 1 (windows 10 latest), any idea what is the new GUID? How to find it?

**Comment by xenolightning** [comment]
The Class ID?!

That's a public Api. It should be listed in the MSDN docs, will go digging.

As a stop gap IUnknown can be used if the class shares the same VTable.

**Comment by sebastso** [comment]
Yes, Class ID. Thanks Sean. The below was working till now, now it does not in RS1.
[ComImport, Guid("870af99c-171d-4f9e-af0d-e63df40c2bc9")]
    internal class _PolicyConfigClient
    {
    }

**Comment by xenolightning** [comment]
I'll have to push my laptop up to RS1, to explore the issue.

A few starting points would be the class registry in regedit for anything in the audses.dll. Would probably be useful to dump every guid that is used by this dll.

The next best option would be to try and extract the guid from the dll itself, this is a complete unknown, and may not be achievable.

**Comment by sebastso** [comment]
WIN 10 RS 1 EEAP Build 14316 to be specific

**Comment by sebastso** [comment]
This is what I'm seeing in the log file about the exception:
 System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CoreAudioApi.Interfaces.IPolicyConfig.SetDefaultEndpoint(String pszDeviceName, ERole role)
   at HPAudioApp.TrayPopupViewModel.SetDevice(Device device) in c:\QA\workspace\HPAudioApp\HPAudioApp\ViewModel\TrayPopupViewModel.cs:line 55

**Comment by xenolightning** [comment]
That stack trace doesn't look to originate from this project. So I can't comment on the validity of it.

However, this issue is still like to affect this project.

**Comment by sebastso** [comment]
Yes, you are correct, it is not from this project, but will affect this project.

**Comment by xenolightning** [comment]
I think I have identified a way to expose the GUID for that class, it works in the current Windows 10 build.

My laptop won't automatically update to redstone insider build, so the confirmation will have to wait until then.

I'm hesitant to publicly announce how I got the information, in-case it gets patched out. But it doesn't require disassembly of the win32 dll's.

**Comment by xenolightning** [comment]
Notes:

GUID is still the same for 14295.rs1

**Comment by xenolightning** [comment]
Works as expected in 14332.rs1

Closing.

**Comment by sebastso** [comment]
Thanks Sean for the update.
