### ISSUE TITLE
Some packages are compatible with UAP version 10.0? (NuGet)

### ISSUE THREAD

**Issue by SanaRinomi** [xenolightning/AudioSwitcher#32]
I'm probably being an idiot, but the NuGet library doesn't install because some of the packages aren't compatible with Windows Universal App Platform (UAP). I'll list the output I got:

`Restoring packages for 'CortanaComponent'.

Restoring packages for C:\Users\User\Documents\Visual Studio 2015\Projects\Cortana\CortanaComponent\project.json...

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0.

Some packages are not compatible with UAP,Version=v10.0.

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-arm).

Some packages are not compatible with UAP,Version=v10.0 (win10-arm).

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-arm-aot).

Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x64).

Some packages are not compatible with UAP,Version=v10.0 (win10-x64).

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x64-aot).

Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x86).

Some packages are not compatible with UAP,Version=v10.0 (win10-x86).

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).

Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).

Package restore failed for 'CortanaComponent'.

Restoring packages for 'HomeControl'.

Restoring packages for C:\Users\User\Documents\Visual Studio 2015\Projects\Cortana\CortanaExt\project.json...

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0.

Some packages are not compatible with UAP,Version=v10.0.

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-arm).

Some packages are not compatible with UAP,Version=v10.0 (win10-arm).

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-arm-aot).

Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x64).

Some packages are not compatible with UAP,Version=v10.0 (win10-x64).

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x64-aot).

Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x86).

Some packages are not compatible with UAP,Version=v10.0 (win10-x86).

AudioSwitcher.AudioApi.CoreAudio 3.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).

Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).

Package restore failed for 'CortanaExt'.

Package restore failed. Rolling back package changes for 'CortanaComponent'.

========== Finished ==========
`

**Comment by xenolightning** [comment]
The CoreAudio library is currently only compatible with full .net implementations on a Windows PC only.

This may change in the future, but it's currently not on the roadmap to create support for multi platforms.

If you are looking for an audio library that is multi platform, (but doesn't include the default switching) checkout https://github.com/naudio/NAudio
