### ISSUE TITLE
Windows 10 Creators Update - RedStone 2 - New PolicyConfig IID

### ISSUE THREAD

**Issue by mitechzone** [xenolightning/AudioSwitcher#33]
Windows 10 changed the IID again in Creators Update.

@xenolightning I suppose you might need the following:

`internal const string POLICY_CONFIG_X_RS2_IID = "098FF37B-1062-4B1A-AD73-2A2D530FEAB6";`

**Comment by xenolightning** [comment]
Thanks, for some reason I can't pull down the creators update. Not sure why.

Once I get it, i'll test that new GUID, and patch the api.

**Comment by xenolightning** [comment]
@mitechzone What Windows build number is causing issues for you?

**Comment by mitechzone** [comment]
Version 1703 (OS Build 15063.13)

**Comment by xenolightning** [comment]
Cool, yep, confirmed that the RS1 iid is no longer used in 15063. 

Have also confirmed the GUID for RS2.

Updated and pushed the code change. 

Thanks for the bug report  👍

**Comment by xenolightning** [comment]
Looks like this also changed in the redstone 3 pre-release. Not sure why they keep changing it, it's not like it's hard to find 😕 

`167fa077-8c46-4f64-b73b-8387c32f251e`
