### ISSUE TITLE
Powershell Module?

### ISSUE THREAD

**Issue by mg07647** [xenolightning/AudioSwitcher#36]
Controlling desktop audio devices via Powershell is exactly what I'm looking for, but the links to the documentation seem to be broken. Also it would be helpful if there was a pre-compiled DLL and a sample script.
Sorry if I just missed any of the above.

**Comment by xenolightning** [comment]
Nope, you didn't miss anything.

I hadn't updated the docs since I moved it into a separate repository.

Check out: https://github.com/xenolightning/AudioSwitcher.PowerShell

It has all the info in it.

**Comment by xenolightning** [comment]
There aren't any docs on how to use it, but feel free to ask any questions.

**Comment by qwelias** [comment]
Hi @xenolightning,

I'm interested in toggling device state (enabled/disabled), is it possible to do with `Get-AudioController`?

**Comment by xenolightning** [comment]
@qwelias Enabling/Disabling devices is outside the scope of the audioswitcher library I'm afraid.

It requires admin access, and to interact with device management.

You might be able to manage device state via powershell, check the following page: https://blogs.technet.microsoft.com/wincat/2012/09/06/device-management-powershell-cmdlets-sample-an-introduction/
