### ISSUE TITLE
SessionDisconnected only fires once for programs with multiple audio sessions

### ISSUE THREAD

**Issue by guyyst** [xenolightning/AudioSwitcher#38]
### Since FireFox is the only program I know of that creates multiple audio sessions, I haven't been able to try this with anything else.

Every time I create a new tab in FireFox, the SessionCreated fires, and a new audio session is also visible in the Windows volume mixer.

When I close one tab, the SessionDisconnected event fires like you would expect, and the session disappears from the Windows volume mixer.

The problem is, that this is the only SessionDisconnected event I will get. Closing any more tabs doesn't fire the event again, and even closing FireFox altogether doesn't work.

_As a side note: Even if the event were to go off for every session created by FireFox, I have no way of knowing which session was actually removed, since the ID is the same for every session. As far as I can tell the only thing differentiating the sessions is the ProcessID._

**Comment by xenolightning** [comment]
What version of the library are you using?

I should be able to confirm this one pretty quickly for you.

**Comment by guyyst** [comment]
v4.0.0-alpha5

**Comment by xenolightning** [comment]
Hmmm, this might be to do with the internals of Firefox, and it's session handling.

You are correct in saying it's not firing disconnected events at all.

It is however firing session expired events. Which could be treated in the same way as a disconnected event.

I'm thinking the disconnect might be more hardware related than software.

As for the session id, yeah it's the same id for each session in firefox. There's no way to change that, it's an id that's generated between firefox and windows, I just expose it internally.

What I'm thinking, is that I will publicly expose the underlying state changes for each session too.

This should allow you to subscribe to the "expired" state event, and remove the session. Thoughts?

**Comment by xenolightning** [comment]
You can currently subscribe to state changes on each session. But it's possibly more useful to have an aggregated endpoint on the controller too?

Like SessionCreated and SessionDisconnected?

**Comment by guyyst** [comment]
I rewrote part of my code to subscribe to each StateChanged event manually, and it indeed works much better. Having all the extra information about an expired state, instead of just the session Id, is awesome as well.

But yeah, I think a SessionStateChanged event for the controller would make this a whole lot easier to manage.

**Comment by xenolightning** [comment]
Cool. I'll create another issue to add session state changes to the controller, and track it there.

Out of interest is the project you are working on open source? Would love to see what you're using it for :)

**Comment by guyyst** [comment]
I've always been annoyed with how cumbersome it is to use the built in Volume Mixer in Windows, so I'm making something that allows me to easily manage the volume of all open applications without taking my hands of the keyboard.

it's currently private, simply because it's a one week old mess that I don't want anyone to see :p, but I'll be making it public soon enough.

Your library's been amazing though. Aside from this minor issue it has been a pleasure to use!

**Comment by xenolightning** [comment]
Oh cool! 

Haha I feel you about the Windows Mixer. I got halfway through re-writing a better mixer app too.

Never made it out a prototype though. Was intending to include the ability "re-route" audio from one application to another output device too.

That's good to hear! I only built it for myself, so it's nice to see that's it's useful elsewhere too!
