### ISSUE TITLE
Can I use GetMasterVolumeLevelScalar with this API?

### ISSUE THREAD

**Issue by AntonioCaroppos** [xenolightning/AudioSwitcher#42]
I have downloaded AudioSwitcher.AudioApi.CoreAudio using NuGet.

I was then trying to use GetMasterVolumeLevelScalar to get the Windows volume. 

However, I don't find this function in the Api.

Could you give me a hint to get the MasterVolumeLevelScalar?

**Comment by xenolightning** [comment]
Calling `CoreAudioDevice.Volume` will return a normalised volume that uses `MasterVolumeLevelScalar` behind the scenes.

The normalised volume is a `double` from `0-100`.

**Comment by xenolightning** [comment]
There is no direct access to the COM functions available. This is a wrapper around the underlying COM functions, to make them more accessible.

If you'd like to interop with COM in a more direct way, I'd suggest taking a look at either [nAudio](https://github.com/naudio/NAudio) or [CSCore](https://github.com/filoe/cscore). Both of which are "closer to the metal"

**Comment by AntonioCaroppos** [comment]
Very nice, thank you!

**Comment by AntonioCaroppos** [comment]
Could you post an example on how to get the volume using VB.NET?

I'm having a problem with this as I can't declare AudioSwitcher.AudioApi.CoreAudio.CoreAudioDevice as a new instance, and using the default instance results in an "Object not defined" compiler error.

**Comment by xenolightning** [comment]
I wouldn't know how to write it in VB.NET sorry. 

You can't initialise CoreAudioDevice as a design decisions, as the devices are managed by the controller.

Try exploring the devices with `controller.GetDevices()` and iterate through the system devices. 

Take a look at https://github.com/xenolightning/AudioSwitcher/blob/master/AudioSwitcher.AudioApi/IAudioController.Generic.cs

And https://github.com/xenolightning/AudioSwitcher/blob/master/AudioSwitcher.AudioApi/IDevice.cs

To see what's possible on the controller and devices in the system

**Comment by AntonioCaroppos** [comment]
VB.NET:

       Using controller As New CoreAudioController()

            Dim dev = controller.DefaultPlaybackDevice

            Dim i As Integer = dev.Volume

        End Using
