### ISSUE TITLE
How to check for disconnected devices?

### ISSUE THREAD

**Issue by AndersEgberts** [xenolightning/AudioSwitcher#47]
Hi, I'm looking for a way to detect when a device has been disconnected. CoreAudioDevice.SessionController.SessionDisconnected is called when a device is disconnected from the machine, but is seems to be only called once, and is not called for subsequent reconnections and disconnections.
You have created issue #39 to expose aggregate session messages through a single point. Have there been any updates regarding this issue?
Is there some other work around to reliably get messages when a device is connected and disconnected?

Kind regards,

Anders Egberts

**Comment by AndersEgberts** [comment]
Is this project still actively worked on?

**Comment by xenolightning** [comment]
I'm not as active on the project as I would like to be sorry.

Are you looking at only detecting when an entire device is disconnected?

You can subscribe to `IAudioController.AudioDeviceChanged` - which will publish `DeviceChangedArgs` or more over `DeviceRemovedArgs` - when a device is disconnected or removed fro the system.

**Comment by AndersEgberts** [comment]
Thanks for the reply.

I've tested the IAudioController events, using a headset that is connected via USB. However, I never got the DeviceRemovedArgs or DeviceAddedArgs when I disconnected/reconnected the device. Instead, I mostly got DeviceStateChangedArgs and DefaultDeviceChangedArgs.
Do the DeviceRemoveArgs and DeviceAddedArgs only occur when a device is connected to the computer for the first time?

**Comment by xenolightning** [comment]
`DeviceAddedArgs` might only be when first connecting.

You should be able to use `DeviceStateChangedArgs`.

Each device will raise `OnStateChanged` when it detects it's own state has changed - which also bubbles up through `AudioController.AudioDeviceChanged`.

The `DeviceStateChangedArgs` contains the new state and the current device.

A disconnected device could give 

```
Disabled = 0x00000002, //caused by device manager disabling the device
NotPresent = 0x00000004, // usb unplugged
Unplugged = 0x00000008, // active but not plugged in eg 3.5mm jack
```

I would expect either NotPresent or Unplugged for a usb device.

For the device becoming available it should raise `DeviceState.Active`

**Comment by AndersEgberts** [comment]
Thanks once again, for the reply (And sorry for my late response)

I've tried using StateChanged directly from the device (IDevice). The event never seems to occur. I've tried the following actions:

- Physically remove USB device
- Enable/Disable device using windows.

However, CoreAudioController does raise the event when the device is unplugged/reattached. So I can rely on that for now.

I am curious as to why the event isn't raised from the device. I am using the latest stable version of the API: version 3.0.0.1. The class that should be notified of the state-change implements IObserver<DeviceStateChangedArgs> and subscribes to the event like this:
`_device.StateChanged.Subscribe(this);`
And processes the event like this:
`public void OnNext(DeviceStateChangedArgs value)
{
    State = value.State;
}`
Am I doing something wrong? Same sort of approach does work for VolumeChanged.

**Comment by xenolightning** [comment]
I'd maybe look at using the 4.0 alpha builds - it improved a lot of the internals around eventing.

I just ran a test app and it raises correct events for devices and aggregates them in the controller too.

```
public Test()
{
    _controller = new CoreAudioController();

    _controller.AudioDeviceChanged.Subscribe(this);

    foreach (var device in _controller.GetPlaybackDevices(DeviceState.Active))
    {
        Console.WriteLine($"{device.FullName} - {device.State}");
        device.StateChanged.Subscribe(this);
    }
}

public void OnNext(DeviceStateChangedArgs value)
{
    Console.WriteLine($"State changed for [{value.Device.FullName}] to [{value.State}]");
}

public void OnNext(DeviceChangedArgs value)
{
    Console.WriteLine($"Device changed for [{value.Device.FullName}] to [{value.ChangedType}]");
}
```

Outputs:
```
DELL U2715H (Intel(R) Display Audio) - Active
Headset (WH-1000XM3 Hands-Free AG Audio) - Active
Speakers (Realtek High Definition Audio) - Active
Headphones (WH-1000XM3 Stereo) - Active
Device changed for [Headset (WH-1000XM3 Hands-Free AG Audio)] to [StateChanged]
State changed for [Headset (WH-1000XM3 Hands-Free AG Audio)] to [Unplugged]
Device changed for [Headset (WH-1000XM3 Hands-Free AG Audio)] to [StateChanged]
Device changed for [Microphone (Realtek High Definition Audio)] to [DefaultChanged]
Device changed for [Headphones (WH-1000XM3 Stereo)] to [StateChanged]
State changed for [Headphones (WH-1000XM3 Stereo)] to [Unplugged]
Device changed for [Speakers (Realtek High Definition Audio)] to [DefaultChanged]
Device changed for [DELL U2715H (Intel(R) Display Audio)] to [DefaultChanged]
Device changed for [Headphones (WH-1000XM3 Stereo)] to [StateChanged]
State changed for [Headphones (WH-1000XM3 Stereo)] to [Active]
Device changed for [Headphones (WH-1000XM3 Stereo)] to [DefaultChanged]
Device changed for [Headphones (WH-1000XM3 Stereo)] to [DefaultChanged]
Device changed for [Headset (WH-1000XM3 Hands-Free AG Audio)] to [StateChanged]
Device changed for [Headset (WH-1000XM3 Hands-Free AG Audio)] to [DefaultChanged]
Device changed for [Headset (WH-1000XM3 Hands-Free AG Audio)] to [StateChanged]
State changed for [Headset (WH-1000XM3 Hands-Free AG Audio)] to [Active]
```

When disconnecting a bluetooth device.

**Comment by AndersEgberts** [comment]
Sorry for the late reply. Your example code has helped me greatly. Thanks!
