### ISSUE TITLE
Add support for Enabling/Disabling Audio Devices

### ISSUE THREAD

**Issue by RehanSaeed** [xenolightning/AudioSwitcher#51]
I'd like to be able to enable or disable audio devices. I can't seem to find a way to do so using the .NET API's, so I assume this feature does not exist.

**Comment by xenolightning** [comment]
There's no "easy" way to do this via .net - you'd need to look at the device api in win32 and P/Invoke.

Out of scope for this library at the moment.

Check out stackoverflow and other resources for more info on the topic:

https://stackoverflow.com/questions/252185/how-do-i-disable-a-system-device
