### ISSUE TITLE
Is possible to make +100% volume?

### ISSUE THREAD

**Issue by GabrielMaestre** [xenolightning/AudioSwitcher#55]
Hi, I'm creating a simple audio project. But I would like to know if I can pass the limit of 100% of the volume (like the google extensions for volumegain) I am programming in C#

**Comment by xenolightning** [comment]
Windows uses a normalized scale for setting volume 0-100. There's no way to set the volume to "200".

To boost the output you'd either need a gain control on the sound device itself - or you'd have to pre-process the sound signal and apply a boost. Both outside the scope of this library as you'd need to create custom drivers or software to do this
