### ISSUE TITLE
Setting default audio device return s false

### ISSUE THREAD

**Issue by VanKurt** [xenolightning/AudioSwitcher#57]
I'm trying to set a default audio device on my computer like so:

`bool ok = device.SetAsDefault();`

Very often (seemingly at random) the call fails and returns false. Is this supposed to happen? Are there any more information available on why/when this happens?

Is there a way to ensure the default device is set?

**Comment by xenolightning** [comment]
What version of the library are you using?

There's some issues in the system when attempting to set default devices - for unknown reasons it can take longer than expected.

There's a 500ms timeout enforced if AudioSwitcher doesn't hear back from the system in that time it assumes it failed.

If you are using the pre-release 4.0 builds, you can use the SetDefaultAsync(CancellationToken) overload.

This will prevent the timeout being enforced, and wait for the signal from the system that it has indeed changed a default.


There's really no way to tell if the system has actioned set default synchronously, so I end up listening for default device changes asynchronously and acknowledging the original set default call. It's a horrible workaround for the underlying library, and hardware interactions

**Comment by xenolightning** [comment]
For more info on what's going on under the hood you can take a look at the set default methods in:

https://github.com/xenolightning/AudioSwitcher/blob/master/AudioSwitcher.AudioApi.CoreAudio/CoreAudioDevice.cs

**Comment by VanKurt** [comment]
I tried to use the asynchronous method:

      var cts = new CancellationTokenSource(TimeSpan.FromSeconds(30));
      var task = device.SetAsDefaultAsync(cts.Token);

      task.Wait();

But this throws an exception:

> Managed Debugging Assistant 'DisconnectedContext' : 'The following error occurred during transition to COM context 0x7d9350 for this RuntimeCallableWrapper: Exception of HRESULT: 0xE0434352. This usually occurs because the COM context 0x7d9350 in which this RuntimeCallableWrapper was created has been disconnected or is busy due to some other operation. The interfaces are released from the current COM context (COM context 0x7d9128). This can result in data corruption or loss. To avoid this problem, you must ensure that all COM contexts/appartments/threads are maintained and available for context transition until the application has fully processed all RuntimeCallableWrappers that represent COM components contained within them.'

Am I using the method the wrong way?

**Comment by xenolightning** [comment]
Calling `.Wait()` on an async method can be pretty dangerous, can cause deadlocks and just weird behaviour.

I just realised there is also a synchronous overload with a cancellation token too.

If you need to call it in a synchronous context I'd first try:

`device.SetDefault(CancellationToken.None)` or use the CancellationTokenSource as you had done above.

Or if you want to call the async method in a synchronous way try:

`Task.Run(async () => await device.SetAsDefaultAsync(token)).ConfigureAwait(false).GetAwaiter().GetResult()` - it's a "safer" way to block on async code. I would avoid this if possible though

**Comment by VanKurt** [comment]
Thanks for your help. I tried all your suggestions, but every call returns immediately. The result is always false.
There seems to be no way to get this working :-(

**Comment by VanKurt** [comment]
Found it :-)
For some reason my device was marked as "unplugged". Thus the call always failed.

**Comment by xenolightning** [comment]
Hah!

That'd do it, glad you got to the bottom of it. Might be something to take into account for sure - checking the device status before trying to set as default
