### ISSUE TITLE
CoreAudio 3.0.1 depends on AudioApi 3.0.0-beta5 in Nuget

### ISSUE THREAD

**Issue by ZeeNastalski** [xenolightning/AudioSwitcher#64]
Hi, 
I've noticed that CoreAudio 3.0.0.1 depends on AudioApi 3.0.0 while
CoreAudio 3.0.1 depends on AudioApi 3.0.0-beta5 in Nuget

![image](https://github.com/xenolightning/AudioSwitcher/assets/7221987/93a220c7-93cb-4ab7-91ac-6703d6b39cf4)

![image](https://github.com/xenolightning/AudioSwitcher/assets/7221987/7b5d0b4d-5c6b-45b4-89df-caae4046d4d5)

Is this intentional?

We are experiencing the problem null reference problem in CoreAudio 3.0.0.1 fixed in patch 3.0.1 
https://github.com/xenolightning/AudioSwitcher/pull/62

When updating to 3.0.1 I am getting this error in visual studio
![image](https://github.com/xenolightning/AudioSwitcher/assets/7221987/486aa596-a9ca-4e3e-97a2-766e26ae383c)

Thanks! 
Zee

**Comment by xenolightning** [comment]
Hmmm, yeah that doesn't seem right. It should only need 3.0.0 - let me check that

**Comment by xenolightning** [comment]
`3.0.3` should fix those version issues

https://www.nuget.org/packages/AudioSwitcher.AudioApi.CoreAudio/3.0.3

I've de-listed the other incorrect versions

**Comment by ZeeNastalski** [comment]
Thank you, I've tested 3.0.3 and everything works perfect. Thank you so much!
